### ISSUE TITLE
oonireport doesn't detect/upload reports

### ISSUE THREAD

**Issue by hellais** [TheTorProject/ooni-probe#423]
was: https://trac.torproject.org/projects/tor/ticket/17564

It seems that oonireport doesnt detect or upload any reports:

```
# ls -1 *yamloo |wc -l
59

# oonireport -f /etc/ooniprobe/oonireport.conf status  
Reports to be uploaded
----------------------
Reports in progress
-------------------
Incomplete reports
------------------

# oonireport -f /etc/ooniprobe/oonireport.conf upload
[no output]
```

**Comment by bassosimone** [comment]
In which directory is `ls -1` run?

Anyway, reading again `OONIBReportLog` code:

- the key fact is that `config.report_log_file` is inspected to understand which reports are to be uploaded, which are in progress, and which are incomplete

- by default (and according to my testing) that file is `self.ooni_home + reporting.yml`. In that specific lepidopter instance, such file is empty (hence my `a3aad913` fix)

- it would be interesting to understand how this log end up being empty.

IIRC @anadahz told me that the issue was that the filesystem was full when he looked into the lepidopter instance to understand what is going on. Let's assume that is the case.

We see that [edit_log()](https://github.com/TheTorProject/ooni-probe/blob/master/ooni/reporter.py#L460) is called whenever there is a change in the reports (at least, this is my understanding of this code, with which I'm not super familiar).

We see that this function opens the file, assumes that the loaded data should not be None, then yields what was loaded and finally (if my understanding of `@contextmanager` is correct) writes again the yaml onto the file. Let us assume that the filesystem is full, and hence than an exception is raised.

What happens to this exception? I see that those log editing functions are called through [run()](https://github.com/TheTorProject/ooni-probe/blob/master/ooni/reporter.py#L438) that sets `unlockAndReturn()` as errback. In turn this errback just releases the lock. So, it is possible that the above exception is filtered here and not propagated.

@hellais @anadahz, does this make sense?

**Comment by anadahz** [comment]
Thanks to @bassosimone we have resolved this!
This bug can be set as INVALID this issue isn't related to oonireport
