### ISSUE TITLE
Adding bisection logic to inputProcessor

### ISSUE THREAD

**Issue by seamustuohy** [TheTorProject/ooni-probe#503]
I have mocked up a few nearly working version of keyword list bisection  and have been playing with placing the bisection logic into the inputProcessor. I did this to separate the keyword testing components from the keyword bisection components. This made the mocked up code is considerable cleaner.

In order to make it functional the individual tests need to be able to pass data to the main test_case.inputs generator that seeds each measurement.

​https://github.com/TheTorProject/ooni-probe/blob/master/ooni/nettest.py#L528-L538

I see this being done in one of two ways.

The first is to leverage an outside data-store that the inputProcessor is pulling from, and the test is populating with results. This adds the addition of new services into the stack for a single test, which I don't see as a useful addition. 

The second option is to use the send() function to push values into the generator. This would be a clean way to provide feedback to the test_case.inputs generator that it could use to bisect the blocked input and provide them on a later iteration. I currently cannot use this method because the test instance passed to each measurement is a new test_case object, and therefore does not have access to the test_case.inputs object that is generating inputs. 

I would be happy to take a pass at passing reference to the test_case.inputs object to the test to get a working prototype working if that is the right path to head down. I wanted to ask in here to see if there might be a more appropriate way. I don't want to head down this path if there are reasons why this would never be merged into the core codebase.

Here is my current bisection functionality mock-up for the interested:
​https://github.com/elationfoundation/ooni-probe/blob/feature/bisect_inputs/ooni/nettests/experimental/bisect_send.py

**Comment by hellais** [comment]
Thanks for putting to the test the OONI test writing API in a very interesting way!

First let me try to understand if I properly understand the problem.

Basically you want to keep some state across different test_cases and have the input of the test_case be set based on this "accumulated" state.
As you rightfully point out `inputs` is currently being reset inside of the `_setUp` method of the `NetTestCase`.
I have looked a bit at the code in question and I don't see a particular reason for us to need to reset the value of inputs. So I think you can even avoid setting `self.inputGenerator  = self.inputs` and modifying the base `NetTest` class to remove the line `self.inputs = None` here: https://github.com/TheTorProject/ooni-probe/blob/master/ooni/nettest.py#L709.

I like the approach of sending values to the `self.inputs` generator and I think this is indeed the cleanest solution so I would take this path.

Looking at your code you should ensure that you yield the packet also a second time because otherwise you will end up skipping some values.
Quoting from (https://docs.python.org/2/reference/expressions.html#generator.send)

> The send() method returns the next value yielded by the generator

This means that the next value of the generator will end up as the return value of your calls to `self.inputGenerator.send(bool)` (https://github.com/elationfoundation/ooni-probe/blob/feature/bisect_inputs/ooni/nettests/experimental/bisect_send.py#L193) and as a result will not be consumed.

To demonstrate what I mean try running:

```
def gen():
    for i in range(10):
        result = yield i
        print("Result {}".format(result))
        # comment and uncomment this line to see that one of the values is skipped.
        # yield i

g = gen()
for i in g:
    print i
    g.send("foo-%d" % i)
```

Happy to discuss this further also on IRC.

**Comment by hellais** [comment]
This is now in master.
