### ISSUE TITLE
Sanitize sensitive HTTP headers

### ISSUE THREAD

**Issue by anadahz** [TheTorProject/ooni-probe#780]
Tests should take care not to expose sensitive HTTP such as `X-WAP-Network-Clientdata` headers that were found to the `http_header_field_manipulation` test.

Examples:
* `X-WAP-Network-Client-IMSI` reveals the International Mobile Subscriber Identity (IMSI) that can identify a mobile user.
* `X-WAP-Network-Client-MSISDN` this header can uniquely identifying a user's subscription number in a GSM or a UMTS mobile network.

**Comment by darkk** [comment]
Every operator has its own names for alike headers and, I think, detecting and blacklisting them should be a process, not a manual action.

**Comment by anadahz** [comment]
The examples in https://github.com/TheTorProject/ooni-probe/issues/780#issue-272781623 are from a specific ISP but probably others are using similar HTTP headers with the `IMSI` and `MSISDN` tags.
I agree that sanitizing sensitive HTTP headers should be a process rather than a manual action and we should make sure to address this as complete as possible.

As of now we are aware of HTTP headers that leak extremely sensitive data revealing the phone number of a user and the unique international mobile subscriber identity. Apart from the privacy risks a malicious entity can mount a series of attacks by exploiting the signalling protocols such as Signalling System No 7 (SS7).

It makes sense to have 2 separate tickets: one on how to address leaking sensitive issues in ooniprobe and another on how to sanitize sensitive HTTP headers in existing OONI data. For the latter (sanitization of HTTP headers in existing OONI data) should the issue be filled in the [ooni-pipeline repository](https://github.com/TheTorProject/ooni-pipeline) or elsewhere?

With response to IP addresses some related work was done in https://github.com/TheTorProject/ooni-probe/pull/685 .

**Comment by hellais** [comment]
I don't think we are going to be including any sanitisation as part of legacy ooni-probe anytime soon. As discussed profusely in various places, the solution of having a hardcoded list of "bad headers" is not scalable and having a list of "good headers" is equaly sub-optimal as it will significantly reduce the usefulness of the test.

What I can do, however, to mitigate the risk of this, is separate the http header field manipulation test into it's own deck, so people that don't want to run this risk can disable it from running automatically.

Would that be an acceptable solution for ooni-probe legacy?

If not I am going to close this as `wontfix` as the issue is already tracked inside of #105 and #1476.

**Comment by bassosimone** [comment]
@hellais wouldn't adding checks to the pipeline mitigate the issue anyway?

**Comment by hellais** [comment]
> wouldn't adding checks to the pipeline mitigate the issue anyway?

correct.

**Comment by bassosimone** [comment]
@hellais then perhaps `wontfix` is good because we don't open another branch, I'd say.

**Comment by darkk** [comment]
> wouldn't adding checks to the pipeline mitigate the issue anyway?

@bassosimone but it puts us into position when we actually HAVE that PII as raw-reports are threated as sacred immutable data pool. That's why I said that we probably want to mitigate it BOTH at pipeline AND OONI Probe. What's your internal lawyer saying regarding that objection? :)

**Comment by bassosimone** [comment]
@darrk, my internal lawyer nods :-)

**Comment by hellais** [comment]
> That's why I said that we probably want to mitigate it BOTH at pipeline AND OONI Probe.

Yup, that's why we have two tickets to address it in both parts. However we can't wind back time and have probes unpublish stuff. Also cleanup on the probe side is tricky to do properly and it's unclear what is the best solution there.

As such the pipeline stopgap solution is the best interim solution.

**Comment by darkk** [comment]
Sorry, I was confused when the ticket was closed with `wontfix`. It was `wontfix` for ooni-probe, but not `wontfix` for the whole problem. The ticket is actually split into three tickets:
- scrub at the MK: measurement-kit/measurement-kit#1473
- mine & scrub at the pipeline: TheTorProject/ooni-pipeline#105
- try to mine at MK: measurement-kit/measurement-kit#1476

**Comment by hellais** [comment]
> The ticket is actually split into three tickets (that are already referenced in other comments)

Precisely: https://github.com/TheTorProject/ooni-probe/issues/780#issuecomment-343551591.

I think https://github.com/measurement-kit/measurement-kit/issues/1473 is perhaps also redundant, but I will let @bassosimone evaluate if he thinks it's best to keep both open nonetheless.
